CREATE TABLE `boms_oxo_basic_vehicle` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `model_code` varchar(50) NOT NULL DEFAULT '' COMMENT '车型',
  `model_year` varchar(50) NOT NULL DEFAULT '' COMMENT '年款',
  `region_option_code` varchar(50) NOT NULL DEFAULT '' COMMENT 'AD00下的所有Option',
  `region_feature_code` varchar(50) NOT NULL DEFAULT '' COMMENT '区域feature_code',
  `drive_option_code` varchar(50) NOT NULL DEFAULT '' COMMENT 'AN00下的所有Option',
  `drive_feature_code` varchar(50) NOT NULL DEFAULT '' COMMENT 'feature_code',
  `sales_version_option_code` varchar(50) NOT NULL DEFAULT '' COMMENT '19AA下的所有Option',
  `sales_version_feature_code` varchar(50) NOT NULL DEFAULT '' COMMENT 'feature_code',
  `status` varchar(50) NOT NULL COMMENT '状态 Active/Inactive',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_user` varchar(32) NOT NULL COMMENT '创建人',
  `update_user` varchar(32) NOT NULL COMMENT '修改人',
  `brand` varchar(32) NOT NULL COMMENT '品牌',
  `maturity` varchar(16) NOT NULL DEFAULT 'U' COMMENT '定义Model/Model Year的成熟度(U代表Under Study,P代表Production)',
  `is_del` smallint NOT NULL DEFAULT '0' COMMENT '1删除 0未删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  COMMENT='oxo表头整车基础配置表';